@host = http://localhost:3000/api

@apiUsers = {{host}}/users
@apiProjects = {{host}}/projects
@apiEducation = {{host}}/education
@apiContacto = {{host}}/contactos
@apiLaboral = {{host}}/laboral


#####################
#       USERS       #
#####################

GET {{apiUsers}}
###
POST {{apiUsers}}
Content-Type: application/json

{
        "nombre": "Juan",
        "apellido": "Pérez",
        "fechaNacimiento": "1990-01-01",
        "trabajoActual": "Full Stack Developer",
        "aboutme": "Soy desarrollador web apasionado por la tecnología.",
        "intereses": ["programación", "diseño", "inteligencia artificial"],
        "facebook": "https://facebook.com/juanperez",
        "twitter": "https://twitter.com/juanperez",
        "instagram": "https://instagram.com/juanperez",
        "linkedin": "https://linkedin.com/in/juanperez",
        "github": "https://github.com/juanperez",
        "websiteURL": "https://juanperez.com"
  }
###

PUT  {{apiUsers}}/677ff61b7384b391b6c9e3ce
Content-Type: application/json

{
        "nombre": "Juan Carlos",
        "apellido": "Castañeda",
        "fechaNacimiento": "1990-04-19",
        "trabajoActual": "Full Stack Developer",
        "aboutme": "Soy desarrollador web apasionado por la tecnología, tengo 2 años de experiencia y aprendizaje continuo en el manejo de tecnologías modernas como Git, NodeJS, MySQL, TypeScript, Angular, Express.js y PHP. Recientemente completé un bootcamp en desarrollo fullstack en Bootcamp ID, lo que me permitió consolidar mis habilidades y fortalecer mi pasión por crear soluciones innovadoras y funcionales. Me entusiasma enfrentar nuevos desafíos, colaborar en equipos dinámicos y seguir creciendo en el mundo del desarrollo web.",
        "intereses": ["programación", "diseño", "inteligencia artificial"],
        "facebook": "https://facebook.com/juanperez",
        "twitter": "https://twitter.com/juanperez",
        "instagram": "https://instagram.com/juanperez",
        "linkedin": "https://linkedin.com/in/juanperez",
        "github": "https://github.com/juanperez",
        "websiteURL": "https://juanperez.com"
  }

###
DELETE {{apiUsers}}/677ff61b7384b391b6c9e3ce







#####################
#      PROJECTS     #
#####################

GET {{apiProjects}}
###
GET {{apiProjects}}/6781163616f88aa85088f4f9
###
POST {{apiProjects}}
Content-Type: application/json

{
        "titulo": "Proyecto 2",
        "descripcion": "Este es un proyecto de desarrollo web aprendidas en Id",
        "tecnologias": ["React", "Node.js", "MongoDB"],
        "categoria": "Desarrollo web",
        "urlGitHub": "https://github.com/jccastaneda0201/proyecto_hotel",
        "urlDemo": "https://github.com/jccastaneda0201/Grupo_Musical",
        "imagenDestacada": "https://via.placeholder.com/150"
  }

###
PUT  {{apiProjects}}/6787c0fa034b6094a74df983
Content-Type: application/json

{
        "titulo": "Proyecto Api-Store",
        "descripcion": "Esta es una api de una tienda virtual creada con node.js ",
        "tecnologias": ["Angular", "Node.js", "MongoDB"],
        "categoria": "Desarrollo web Angular",
        "urlGitHub": "https://github.com/jccastaneda0201/api-store",
        "urlDemo": "https://github.com/jccastaneda0201/Grupo_Musical",
        "imagenDestacada": "https://via.placeholder.com/150"
  }

###
DELETE {{apiProjects}}/6780058e116a9eb66c4e2f02




#####################
#     EDUCATION     #
#####################

GET {{apiEducation}}
###
POST {{apiEducation}}
Content-Type: application/json

{
        "institucion": "Universidad de La Laguna",
        "titulo": "Ingeniería Informática",
        "fechaInicio": "2015-09-01",
        "fechaFin": "2020-06-01",
        "descripcion": "Estudios de Ingeniería Informática en la Universidad de La Laguna.",
        "skillTitle": "FULL STACK DEVELOPER",
        "skillDescription": "Desarrollo de aplicaciones web, gestión de bases de datos, y desarrollo de APIs.",
        "tecnologias": ["HTML", "CSS", "JavaScript", "Node.js", "MongoDB"]
  }
###
PUT  {{apiEducation}}/6780071dc980cd9692901837
Content-Type: application/json

{
        "institucion": "BootCamp ID",
        "titulo": "Full Stack Developer",
        "fechaInicio": "2015-09-01",
        "fechaFin": "2020-06-01",
        "descripcion": "Estudios de Ingeniería Informática en la Universidad de La Laguna.",
        "skillTitle": "Angular",
        "skillDescription": "Desarrollo de aplicaciones web, gestión de bases de datos, y desarrollo de APIs.",
        "tecnologias": ["HTML", "CSS", "JavaScript", "Node.js", "MongoDB"]
  }

###
DELETE {{apiEducation}}/6780071dc980cd9692901837


#####################
#     CONTACTOS    #
#####################
GET {{host}}/contactos
###
POST {{host}}/contactos
Content-Type: application/json

{
        "nombre": "Juan Sebastian Martinez",
        "email": "juan.perez@gmail.com",
        "asunto": "Proyecto Laboral",
        "mensaje": "Hola, me gustaría contactar contigo para hablar sobre un proyecto."
  }
###
PUT  {{host}}/contactos/678114c632a699754a30ee79
Content-Type: application/json

{
        "nombre": "Juan Carlos",
        "apellido": "Castañeda",
        "asunto": "Proyecto Laboral",
        "email": "any",
        "mensaje": "Hola, me gustaría contactar contigo para hablar sobre un proyecto."
  }

###
DELETE {{host}}/contactos/678114c632a699754a30ee79

#####################
#     LABORAL       #
#####################
GET {{host}}/laboral
###
GET {{host}}/laboral/67879cd0a20fab876a8e452f
###
POST {{host}}/laboral
Content-Type: application/json

{
  "titulo": "Desarrollador Full Stack",
  "empresa": "Umbrella Solutions",
  "ubicacion": "Barcelona, España",
  "fechaInicio": "2018-07-01",
  "fechaFin": "2021-12-31", 
  "actual": false, 
  "funciones":[
    "Participé en el equipo de creación y desarrollo del front-end de una web app de inicio a fin ayudando a su desarrollo y mejora en sus iteraciones con Next.js.",
    "Desarrollo y mantenimiento de diferentes interfaces de administración de productos digitales.",
    "Integración de servicios de tercero en el front-end en diferentes proyectos de web apps como Firebase Realtime DB, Firestore o Stripe.",
    "Refactorización de código ya existente para hacerlo más escalable, mantenible y óptimo en rendimiento y legibilidad.",
    "Desarrollo de landing pages con el framework Astro, aplicando buenas prácticas y metodología BEM."
  ],
  "descripcion": "Empresa de diseño y desarrollo de productos y soluciones digitales",
  "habilidades": ["React", "Node.js", "MongoDB", "Express", "TypeScript"]
}
###
PUT  {{host}}/laboral/6781173316f88aa85088f505
Content-Type: application/json

{
  "titulo": "Desarrollador Full Stack",
  "empresa": "Umbrella Solutions",
  "ubicacion": "Ciudad de México, México",
  "fechaInicio": "2018-07-01",
  "fechaFin": "2021-12-31", 
  "actual": false, 
  "funciones":[
    "Participé en el equipo de creación y desarrollo del front-end de una web app de inicio a fin ayudando a su desarrollo y mejora en sus iteraciones con Next.js.",
    "Desarrollo y mantenimiento de diferentes interfaces de administración de productos digitales.",
    "Integración de servicios de tercero en el front-end en diferentes proyectos de web apps como Firebase Realtime DB, Firestore o Stripe.",
    "Refactorización de código ya existente para hacerlo más escalable, mantenible y óptimo en rendimiento y legibilidad.",
    "Desarrollo de landing pages con el framework Astro, aplicando buenas prácticas y metodología BEM."
  ],
  "descripcion": "Empresa de diseño y desarrollo de productos y soluciones digitales",
  "habilidades": ["React", "Node.js", "MongoDB", "Express", "TypeScript"]
}
###
DELETE {{host}}/laboral/678116ac16f88aa85088f4ff

